###
# THIS FILE IS AUTOMATICALLY GENERATED
# Do not edit this file. It will be overwritten when the configure script is run.
###

######
# Build ID: aef548c0
# Executable: /Users/DHRUVA/Desktop/ChampSimExperiments/bin/champsim
######

###
# Build ID: aef548c0
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/src
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/obj
###

aef548c0_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/obj
aef548c0_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/src/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/obj/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/src/*.cc))
$(aef548c0_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/src
$(aef548c0_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/obj/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/src/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/obj
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/obj/*.d)

/Users/DHRUVA/Desktop/ChampSimExperiments/bin/champsim: $(aef548c0_objs_0) | /Users/DHRUVA/Desktop/ChampSimExperiments/bin
$(aef548c0_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/inc
build_dirs += $(aef548c0_dirs_0) /Users/DHRUVA/Desktop/ChampSimExperiments/bin
build_objs += $(aef548c0_objs_0)
executable_name += /Users/DHRUVA/Desktop/ChampSimExperiments/bin/champsim

###
# Build ID: aef548c0_btbDbasic_btb
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/btb/basic_btb
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/btbDbasic_btb
###

aef548c0_btbDbasic_btb_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/btbDbasic_btb
aef548c0_btbDbasic_btb_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/btb/basic_btb/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/btbDbasic_btb/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/btb/basic_btb/*.cc))
$(aef548c0_btbDbasic_btb_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/btb/basic_btb
$(aef548c0_btbDbasic_btb_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/btbDbasic_btb/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/btb/basic_btb/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/btbDbasic_btb
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/btbDbasic_btb/*.d)

$(aef548c0_btbDbasic_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
$(aef548c0_btbDbasic_btb_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(aef548c0_btbDbasic_btb_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/inc
$(aef548c0_btbDbasic_btb_objs_0): CPPFLAGS += -include btbDbasic_btb.inc
module_dirs += $(aef548c0_btbDbasic_btb_dirs_0)
module_objs += $(aef548c0_btbDbasic_btb_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/bin/champsim: $(aef548c0_btbDbasic_btb_objs_0)
###
# Build ID: aef548c0_branchDbimodal
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/branch/bimodal
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/branchDbimodal
###

aef548c0_branchDbimodal_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/branchDbimodal
aef548c0_branchDbimodal_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/branch/bimodal/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/branchDbimodal/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/branch/bimodal/*.cc))
$(aef548c0_branchDbimodal_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/branch/bimodal
$(aef548c0_branchDbimodal_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/branchDbimodal/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/branch/bimodal/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/branchDbimodal
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/branchDbimodal/*.d)

$(aef548c0_branchDbimodal_objs_0): CXXFLAGS += -Wno-unused-parameter
$(aef548c0_branchDbimodal_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(aef548c0_branchDbimodal_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/inc
$(aef548c0_branchDbimodal_objs_0): CPPFLAGS += -include branchDbimodal.inc
module_dirs += $(aef548c0_branchDbimodal_dirs_0)
module_objs += $(aef548c0_branchDbimodal_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/bin/champsim: $(aef548c0_branchDbimodal_objs_0)
###
# Build ID: aef548c0_prefetcherDno
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno
###

aef548c0_prefetcherDno_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno
aef548c0_prefetcherDno_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no/*.cc))
$(aef548c0_prefetcherDno_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no
$(aef548c0_prefetcherDno_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno/*.d)

$(aef548c0_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
$(aef548c0_prefetcherDno_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(aef548c0_prefetcherDno_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/inc
$(aef548c0_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
module_dirs += $(aef548c0_prefetcherDno_dirs_0)
module_objs += $(aef548c0_prefetcherDno_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/bin/champsim: $(aef548c0_prefetcherDno_objs_0)
###
# Build ID: aef548c0_prefetcherDno_instr
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no_instr
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno_instr
###

aef548c0_prefetcherDno_instr_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno_instr
aef548c0_prefetcherDno_instr_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no_instr/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno_instr/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no_instr/*.cc))
$(aef548c0_prefetcherDno_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no_instr
$(aef548c0_prefetcherDno_instr_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno_instr/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no_instr/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno_instr
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/prefetcherDno_instr/*.d)

$(aef548c0_prefetcherDno_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
$(aef548c0_prefetcherDno_instr_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(aef548c0_prefetcherDno_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/inc
$(aef548c0_prefetcherDno_instr_objs_0): CPPFLAGS += -include prefetcherDno_instr.inc
module_dirs += $(aef548c0_prefetcherDno_instr_dirs_0)
module_objs += $(aef548c0_prefetcherDno_instr_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/bin/champsim: $(aef548c0_prefetcherDno_instr_objs_0)
###
# Build ID: aef548c0_replacementDlru
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/lru
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/replacementDlru
###

aef548c0_replacementDlru_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/replacementDlru
aef548c0_replacementDlru_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/lru/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/replacementDlru/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/lru/*.cc))
$(aef548c0_replacementDlru_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/replacement/lru
$(aef548c0_replacementDlru_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/replacementDlru/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/lru/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/replacementDlru
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/replacementDlru/*.d)

$(aef548c0_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
$(aef548c0_replacementDlru_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(aef548c0_replacementDlru_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/aef548c0/inc
$(aef548c0_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
module_dirs += $(aef548c0_replacementDlru_dirs_0)
module_objs += $(aef548c0_replacementDlru_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/bin/champsim: $(aef548c0_replacementDlru_objs_0)

######
# Build ID: 5b903751
# Executable: /Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main
######

###
# Build ID: 5b903751
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/src
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj
###

5b903751_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj
5b903751_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/src/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/src/*.cc))
$(5b903751_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/src
$(5b903751_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/src/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj/*.d)

###
# Build ID: 5b903751
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/src
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj
###

5b903751_dirs_1 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj
5b903751_objs_1 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/src/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/src/*.cc))
$(5b903751_objs_1): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/src
$(5b903751_objs_1): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/src/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/obj/*.d)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_objs_0) $(5b903751_objs_1) | /Users/DHRUVA/Desktop/ChampSimExperiments/test/bin
$(5b903751_objs_0) $(5b903751_objs_1): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
build_dirs += $(5b903751_dirs_0) $(5b903751_dirs_1) /Users/DHRUVA/Desktop/ChampSimExperiments/test/bin
build_objs += $(5b903751_objs_0) $(5b903751_objs_1)
executable_name += /Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main

###
# Build ID: 5b903751_btbDbasic_btb
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/btb/basic_btb
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/btbDbasic_btb
###

5b903751_btbDbasic_btb_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/btbDbasic_btb
5b903751_btbDbasic_btb_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/btb/basic_btb/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/btbDbasic_btb/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/btb/basic_btb/*.cc))
$(5b903751_btbDbasic_btb_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/btb/basic_btb
$(5b903751_btbDbasic_btb_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/btbDbasic_btb/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/btb/basic_btb/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/btbDbasic_btb
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/btbDbasic_btb/*.d)

$(5b903751_btbDbasic_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_btbDbasic_btb_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_btbDbasic_btb_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_btbDbasic_btb_objs_0): CPPFLAGS += -include btbDbasic_btb.inc
module_dirs += $(5b903751_btbDbasic_btb_dirs_0)
module_objs += $(5b903751_btbDbasic_btb_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_btbDbasic_btb_objs_0)
###
# Build ID: 5b903751_branchDbimodal
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/branch/bimodal
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDbimodal
###

5b903751_branchDbimodal_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDbimodal
5b903751_branchDbimodal_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/branch/bimodal/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDbimodal/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/branch/bimodal/*.cc))
$(5b903751_branchDbimodal_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/branch/bimodal
$(5b903751_branchDbimodal_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDbimodal/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/branch/bimodal/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDbimodal
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDbimodal/*.d)

$(5b903751_branchDbimodal_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_branchDbimodal_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_branchDbimodal_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_branchDbimodal_objs_0): CPPFLAGS += -include branchDbimodal.inc
module_dirs += $(5b903751_branchDbimodal_dirs_0)
module_objs += $(5b903751_branchDbimodal_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_branchDbimodal_objs_0)
###
# Build ID: 5b903751_branchDgshare
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/branch/gshare
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDgshare
###

5b903751_branchDgshare_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDgshare
5b903751_branchDgshare_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/branch/gshare/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDgshare/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/branch/gshare/*.cc))
$(5b903751_branchDgshare_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/branch/gshare
$(5b903751_branchDgshare_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDgshare/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/branch/gshare/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDgshare
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDgshare/*.d)

$(5b903751_branchDgshare_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_branchDgshare_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_branchDgshare_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_branchDgshare_objs_0): CPPFLAGS += -include branchDgshare.inc
module_dirs += $(5b903751_branchDgshare_dirs_0)
module_objs += $(5b903751_branchDgshare_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_branchDgshare_objs_0)
###
# Build ID: 5b903751_branchDhashed_perceptron
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/branch/hashed_perceptron
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDhashed_perceptron
###

5b903751_branchDhashed_perceptron_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDhashed_perceptron
5b903751_branchDhashed_perceptron_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/branch/hashed_perceptron/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDhashed_perceptron/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/branch/hashed_perceptron/*.cc))
$(5b903751_branchDhashed_perceptron_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/branch/hashed_perceptron
$(5b903751_branchDhashed_perceptron_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDhashed_perceptron/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/branch/hashed_perceptron/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDhashed_perceptron
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDhashed_perceptron/*.d)

$(5b903751_branchDhashed_perceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_branchDhashed_perceptron_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_branchDhashed_perceptron_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_branchDhashed_perceptron_objs_0): CPPFLAGS += -include branchDhashed_perceptron.inc
module_dirs += $(5b903751_branchDhashed_perceptron_dirs_0)
module_objs += $(5b903751_branchDhashed_perceptron_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_branchDhashed_perceptron_objs_0)
###
# Build ID: 5b903751_branchDperceptron
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/branch/perceptron
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDperceptron
###

5b903751_branchDperceptron_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDperceptron
5b903751_branchDperceptron_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/branch/perceptron/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDperceptron/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/branch/perceptron/*.cc))
$(5b903751_branchDperceptron_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/branch/perceptron
$(5b903751_branchDperceptron_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDperceptron/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/branch/perceptron/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDperceptron
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/branchDperceptron/*.d)

$(5b903751_branchDperceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_branchDperceptron_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_branchDperceptron_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_branchDperceptron_objs_0): CPPFLAGS += -include branchDperceptron.inc
module_dirs += $(5b903751_branchDperceptron_dirs_0)
module_objs += $(5b903751_branchDperceptron_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_branchDperceptron_objs_0)
###
# Build ID: 5b903751_prefetcherDip_stride
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/ip_stride
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDip_stride
###

5b903751_prefetcherDip_stride_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDip_stride
5b903751_prefetcherDip_stride_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/ip_stride/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDip_stride/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/ip_stride/*.cc))
$(5b903751_prefetcherDip_stride_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/ip_stride
$(5b903751_prefetcherDip_stride_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDip_stride/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/ip_stride/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDip_stride
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDip_stride/*.d)

$(5b903751_prefetcherDip_stride_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_prefetcherDip_stride_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_prefetcherDip_stride_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_prefetcherDip_stride_objs_0): CPPFLAGS += -include prefetcherDip_stride.inc
module_dirs += $(5b903751_prefetcherDip_stride_dirs_0)
module_objs += $(5b903751_prefetcherDip_stride_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_prefetcherDip_stride_objs_0)
###
# Build ID: 5b903751_prefetcherDnext_line
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/next_line
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line
###

5b903751_prefetcherDnext_line_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line
5b903751_prefetcherDnext_line_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/next_line/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/next_line/*.cc))
$(5b903751_prefetcherDnext_line_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/next_line
$(5b903751_prefetcherDnext_line_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/next_line/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line/*.d)

$(5b903751_prefetcherDnext_line_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_prefetcherDnext_line_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_prefetcherDnext_line_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_prefetcherDnext_line_objs_0): CPPFLAGS += -include prefetcherDnext_line.inc
module_dirs += $(5b903751_prefetcherDnext_line_dirs_0)
module_objs += $(5b903751_prefetcherDnext_line_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_prefetcherDnext_line_objs_0)
###
# Build ID: 5b903751_prefetcherDnext_line_instr
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/next_line_instr
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line_instr
###

5b903751_prefetcherDnext_line_instr_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line_instr
5b903751_prefetcherDnext_line_instr_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/next_line_instr/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line_instr/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/next_line_instr/*.cc))
$(5b903751_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/next_line_instr
$(5b903751_prefetcherDnext_line_instr_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line_instr/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/next_line_instr/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line_instr
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDnext_line_instr/*.d)

$(5b903751_prefetcherDnext_line_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -include prefetcherDnext_line_instr.inc
module_dirs += $(5b903751_prefetcherDnext_line_instr_dirs_0)
module_objs += $(5b903751_prefetcherDnext_line_instr_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_prefetcherDnext_line_instr_objs_0)
###
# Build ID: 5b903751_prefetcherDno
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno
###

5b903751_prefetcherDno_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno
5b903751_prefetcherDno_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no/*.cc))
$(5b903751_prefetcherDno_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no
$(5b903751_prefetcherDno_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno/*.d)

$(5b903751_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_prefetcherDno_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_prefetcherDno_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
module_dirs += $(5b903751_prefetcherDno_dirs_0)
module_objs += $(5b903751_prefetcherDno_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_prefetcherDno_objs_0)
###
# Build ID: 5b903751_prefetcherDno_instr
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no_instr
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno_instr
###

5b903751_prefetcherDno_instr_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno_instr
5b903751_prefetcherDno_instr_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no_instr/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno_instr/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no_instr/*.cc))
$(5b903751_prefetcherDno_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no_instr
$(5b903751_prefetcherDno_instr_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno_instr/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/no_instr/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno_instr
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDno_instr/*.d)

$(5b903751_prefetcherDno_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_prefetcherDno_instr_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_prefetcherDno_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_prefetcherDno_instr_objs_0): CPPFLAGS += -include prefetcherDno_instr.inc
module_dirs += $(5b903751_prefetcherDno_instr_dirs_0)
module_objs += $(5b903751_prefetcherDno_instr_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_prefetcherDno_instr_objs_0)
###
# Build ID: 5b903751_prefetcherDspp_dev
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/spp_dev
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDspp_dev
###

5b903751_prefetcherDspp_dev_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDspp_dev
5b903751_prefetcherDspp_dev_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/spp_dev/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDspp_dev/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/spp_dev/*.cc))
$(5b903751_prefetcherDspp_dev_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/spp_dev
$(5b903751_prefetcherDspp_dev_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDspp_dev/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/spp_dev/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDspp_dev
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDspp_dev/*.d)

$(5b903751_prefetcherDspp_dev_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_prefetcherDspp_dev_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_prefetcherDspp_dev_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_prefetcherDspp_dev_objs_0): CPPFLAGS += -include prefetcherDspp_dev.inc
module_dirs += $(5b903751_prefetcherDspp_dev_dirs_0)
module_objs += $(5b903751_prefetcherDspp_dev_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_prefetcherDspp_dev_objs_0)
###
# Build ID: 5b903751_prefetcherDva_ampm_lite
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/va_ampm_lite
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDva_ampm_lite
###

5b903751_prefetcherDva_ampm_lite_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDva_ampm_lite
5b903751_prefetcherDva_ampm_lite_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/va_ampm_lite/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDva_ampm_lite/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/va_ampm_lite/*.cc))
$(5b903751_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/va_ampm_lite
$(5b903751_prefetcherDva_ampm_lite_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDva_ampm_lite/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/prefetcher/va_ampm_lite/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDva_ampm_lite
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/prefetcherDva_ampm_lite/*.d)

$(5b903751_prefetcherDva_ampm_lite_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -include prefetcherDva_ampm_lite.inc
module_dirs += $(5b903751_prefetcherDva_ampm_lite_dirs_0)
module_objs += $(5b903751_prefetcherDva_ampm_lite_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_prefetcherDva_ampm_lite_objs_0)
###
# Build ID: 5b903751_testDcppDmodulesDprefetcherDaddress_collector
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/address_collector
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDaddress_collector
###

5b903751_testDcppDmodulesDprefetcherDaddress_collector_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDaddress_collector
5b903751_testDcppDmodulesDprefetcherDaddress_collector_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/address_collector/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDaddress_collector/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/address_collector/*.cc))
$(5b903751_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/address_collector
$(5b903751_testDcppDmodulesDprefetcherDaddress_collector_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDaddress_collector/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/address_collector/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDaddress_collector
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDaddress_collector/*.d)

$(5b903751_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDaddress_collector.inc
module_dirs += $(5b903751_testDcppDmodulesDprefetcherDaddress_collector_dirs_0)
module_objs += $(5b903751_testDcppDmodulesDprefetcherDaddress_collector_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_testDcppDmodulesDprefetcherDaddress_collector_objs_0)
###
# Build ID: 5b903751_testDcppDmodulesDprefetcherDmetadata_collector
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/metadata_collector
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_collector
###

5b903751_testDcppDmodulesDprefetcherDmetadata_collector_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_collector
5b903751_testDcppDmodulesDprefetcherDmetadata_collector_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/metadata_collector/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_collector/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/metadata_collector/*.cc))
$(5b903751_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/metadata_collector
$(5b903751_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_collector/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/metadata_collector/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_collector
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_collector/*.d)

$(5b903751_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDmetadata_collector.inc
module_dirs += $(5b903751_testDcppDmodulesDprefetcherDmetadata_collector_dirs_0)
module_objs += $(5b903751_testDcppDmodulesDprefetcherDmetadata_collector_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_testDcppDmodulesDprefetcherDmetadata_collector_objs_0)
###
# Build ID: 5b903751_testDcppDmodulesDprefetcherDmetadata_emitter
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/metadata_emitter
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_emitter
###

5b903751_testDcppDmodulesDprefetcherDmetadata_emitter_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_emitter
5b903751_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/metadata_emitter/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_emitter/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/metadata_emitter/*.cc))
$(5b903751_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/metadata_emitter
$(5b903751_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_emitter/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/metadata_emitter/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_emitter
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDmetadata_emitter/*.d)

$(5b903751_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDmetadata_emitter.inc
module_dirs += $(5b903751_testDcppDmodulesDprefetcherDmetadata_emitter_dirs_0)
module_objs += $(5b903751_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0)
###
# Build ID: 5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/prefetch_hit_collector
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDprefetch_hit_collector
###

5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDprefetch_hit_collector
5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/prefetch_hit_collector/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDprefetch_hit_collector/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/prefetch_hit_collector/*.cc))
$(5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/prefetch_hit_collector
$(5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDprefetch_hit_collector/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/prefetcher/prefetch_hit_collector/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDprefetch_hit_collector
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDprefetcherDprefetch_hit_collector/*.d)

$(5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDprefetch_hit_collector.inc
module_dirs += $(5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector_dirs_0)
module_objs += $(5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0)
###
# Build ID: 5b903751_replacementDdrrip
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/drrip
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDdrrip
###

5b903751_replacementDdrrip_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDdrrip
5b903751_replacementDdrrip_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/drrip/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDdrrip/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/drrip/*.cc))
$(5b903751_replacementDdrrip_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/replacement/drrip
$(5b903751_replacementDdrrip_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDdrrip/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/drrip/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDdrrip
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDdrrip/*.d)

$(5b903751_replacementDdrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_replacementDdrrip_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_replacementDdrrip_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_replacementDdrrip_objs_0): CPPFLAGS += -include replacementDdrrip.inc
module_dirs += $(5b903751_replacementDdrrip_dirs_0)
module_objs += $(5b903751_replacementDdrrip_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_replacementDdrrip_objs_0)
###
# Build ID: 5b903751_replacementDlru
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/lru
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDlru
###

5b903751_replacementDlru_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDlru
5b903751_replacementDlru_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/lru/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDlru/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/lru/*.cc))
$(5b903751_replacementDlru_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/replacement/lru
$(5b903751_replacementDlru_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDlru/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/lru/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDlru
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDlru/*.d)

$(5b903751_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_replacementDlru_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_replacementDlru_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
module_dirs += $(5b903751_replacementDlru_dirs_0)
module_objs += $(5b903751_replacementDlru_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_replacementDlru_objs_0)
###
# Build ID: 5b903751_replacementDship
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/ship
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDship
###

5b903751_replacementDship_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDship
5b903751_replacementDship_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/ship/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDship/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/ship/*.cc))
$(5b903751_replacementDship_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/replacement/ship
$(5b903751_replacementDship_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDship/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/ship/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDship
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDship/*.d)

$(5b903751_replacementDship_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_replacementDship_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_replacementDship_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_replacementDship_objs_0): CPPFLAGS += -include replacementDship.inc
module_dirs += $(5b903751_replacementDship_dirs_0)
module_objs += $(5b903751_replacementDship_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_replacementDship_objs_0)
###
# Build ID: 5b903751_replacementDsrrip
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/srrip
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDsrrip
###

5b903751_replacementDsrrip_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDsrrip
5b903751_replacementDsrrip_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/srrip/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDsrrip/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/srrip/*.cc))
$(5b903751_replacementDsrrip_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/replacement/srrip
$(5b903751_replacementDsrrip_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDsrrip/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/replacement/srrip/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDsrrip
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/replacementDsrrip/*.d)

$(5b903751_replacementDsrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_replacementDsrrip_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_replacementDsrrip_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_replacementDsrrip_objs_0): CPPFLAGS += -include replacementDsrrip.inc
module_dirs += $(5b903751_replacementDsrrip_dirs_0)
module_objs += $(5b903751_replacementDsrrip_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_replacementDsrrip_objs_0)
###
# Build ID: 5b903751_testDcppDmodulesDreplacementDlru_collect
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/replacement/lru_collect
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDlru_collect
###

5b903751_testDcppDmodulesDreplacementDlru_collect_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDlru_collect
5b903751_testDcppDmodulesDreplacementDlru_collect_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/replacement/lru_collect/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDlru_collect/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/replacement/lru_collect/*.cc))
$(5b903751_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/replacement/lru_collect
$(5b903751_testDcppDmodulesDreplacementDlru_collect_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDlru_collect/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/replacement/lru_collect/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDlru_collect
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDlru_collect/*.d)

$(5b903751_testDcppDmodulesDreplacementDlru_collect_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -include testDcppDmodulesDreplacementDlru_collect.inc
module_dirs += $(5b903751_testDcppDmodulesDreplacementDlru_collect_dirs_0)
module_objs += $(5b903751_testDcppDmodulesDreplacementDlru_collect_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_testDcppDmodulesDreplacementDlru_collect_objs_0)
###
# Build ID: 5b903751_testDcppDmodulesDreplacementDmock_replacement
# Source: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/replacement/mock_replacement
# Destination: /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDmock_replacement
###

5b903751_testDcppDmodulesDreplacementDmock_replacement_dirs_0 = /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDmock_replacement
5b903751_testDcppDmodulesDreplacementDmock_replacement_objs_0 = $(patsubst /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/replacement/mock_replacement/%.cc, /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDmock_replacement/%.o, $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/replacement/mock_replacement/*.cc))
$(5b903751_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/replacement/mock_replacement
$(5b903751_testDcppDmodulesDreplacementDmock_replacement_objs_0): /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDmock_replacement/%.o: /Users/DHRUVA/Desktop/ChampSimExperiments/test/cpp/modules/replacement/mock_replacement/%.cc | /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDmock_replacement
-include $(wildcard /Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/testDcppDmodulesDreplacementDmock_replacement/*.d)

$(5b903751_testDcppDmodulesDreplacementDmock_replacement_objs_0): CXXFLAGS += -Wno-unused-parameter
$(5b903751_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(5b903751_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -I/Users/DHRUVA/Desktop/ChampSimExperiments/.csconfig/test/5b903751/inc
$(5b903751_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -include testDcppDmodulesDreplacementDmock_replacement.inc
module_dirs += $(5b903751_testDcppDmodulesDreplacementDmock_replacement_dirs_0)
module_objs += $(5b903751_testDcppDmodulesDreplacementDmock_replacement_objs_0)

/Users/DHRUVA/Desktop/ChampSimExperiments/test/bin/000-test-main: $(5b903751_testDcppDmodulesDreplacementDmock_replacement_objs_0)
