###
# THIS FILE IS AUTOMATICALLY GENERATED
# Do not edit this file. It will be overwritten when the configure script is run.
###

######
# Build ID: ae4ea10e
# Executable: /Users/DHRUVA/ChampSim/bin/champsim
######

###
# Build ID: ae4ea10e
# Source: /Users/DHRUVA/ChampSim/src
# Destination: /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/obj
###

ae4ea10e_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/obj
ae4ea10e_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/src/%.cc, /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/obj/%.o, $(wildcard /Users/DHRUVA/ChampSim/src/*.cc))
$(ae4ea10e_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/src
$(ae4ea10e_objs_0): /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/obj/%.o: /Users/DHRUVA/ChampSim/src/%.cc | /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/obj
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/obj/*.d)

/Users/DHRUVA/ChampSim/bin/champsim: $(ae4ea10e_objs_0) | /Users/DHRUVA/ChampSim/bin
$(ae4ea10e_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/inc
build_dirs += $(ae4ea10e_dirs_0) /Users/DHRUVA/ChampSim/bin
build_objs += $(ae4ea10e_objs_0)
executable_name += /Users/DHRUVA/ChampSim/bin/champsim

###
# Build ID: ae4ea10e_btbDbasic_btb
# Source: /Users/DHRUVA/ChampSim/btb/basic_btb
# Destination: /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/btbDbasic_btb
###

ae4ea10e_btbDbasic_btb_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/btbDbasic_btb
ae4ea10e_btbDbasic_btb_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/btb/basic_btb/%.cc, /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/btbDbasic_btb/%.o, $(wildcard /Users/DHRUVA/ChampSim/btb/basic_btb/*.cc))
$(ae4ea10e_btbDbasic_btb_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/btb/basic_btb
$(ae4ea10e_btbDbasic_btb_objs_0): /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/btbDbasic_btb/%.o: /Users/DHRUVA/ChampSim/btb/basic_btb/%.cc | /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/btbDbasic_btb
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/btbDbasic_btb/*.d)

$(ae4ea10e_btbDbasic_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
$(ae4ea10e_btbDbasic_btb_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(ae4ea10e_btbDbasic_btb_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/inc
$(ae4ea10e_btbDbasic_btb_objs_0): CPPFLAGS += -include btbDbasic_btb.inc
module_dirs += $(ae4ea10e_btbDbasic_btb_dirs_0)
module_objs += $(ae4ea10e_btbDbasic_btb_objs_0)

/Users/DHRUVA/ChampSim/bin/champsim: $(ae4ea10e_btbDbasic_btb_objs_0)
###
# Build ID: ae4ea10e_branchDbimodal
# Source: /Users/DHRUVA/ChampSim/branch/bimodal
# Destination: /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/branchDbimodal
###

ae4ea10e_branchDbimodal_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/branchDbimodal
ae4ea10e_branchDbimodal_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/branch/bimodal/%.cc, /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/branchDbimodal/%.o, $(wildcard /Users/DHRUVA/ChampSim/branch/bimodal/*.cc))
$(ae4ea10e_branchDbimodal_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/branch/bimodal
$(ae4ea10e_branchDbimodal_objs_0): /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/branchDbimodal/%.o: /Users/DHRUVA/ChampSim/branch/bimodal/%.cc | /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/branchDbimodal
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/branchDbimodal/*.d)

$(ae4ea10e_branchDbimodal_objs_0): CXXFLAGS += -Wno-unused-parameter
$(ae4ea10e_branchDbimodal_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(ae4ea10e_branchDbimodal_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/inc
$(ae4ea10e_branchDbimodal_objs_0): CPPFLAGS += -include branchDbimodal.inc
module_dirs += $(ae4ea10e_branchDbimodal_dirs_0)
module_objs += $(ae4ea10e_branchDbimodal_objs_0)

/Users/DHRUVA/ChampSim/bin/champsim: $(ae4ea10e_branchDbimodal_objs_0)
###
# Build ID: ae4ea10e_prefetcherDno
# Source: /Users/DHRUVA/ChampSim/prefetcher/no
# Destination: /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno
###

ae4ea10e_prefetcherDno_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno
ae4ea10e_prefetcherDno_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/prefetcher/no/%.cc, /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno/%.o, $(wildcard /Users/DHRUVA/ChampSim/prefetcher/no/*.cc))
$(ae4ea10e_prefetcherDno_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/prefetcher/no
$(ae4ea10e_prefetcherDno_objs_0): /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno/%.o: /Users/DHRUVA/ChampSim/prefetcher/no/%.cc | /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno/*.d)

$(ae4ea10e_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
$(ae4ea10e_prefetcherDno_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(ae4ea10e_prefetcherDno_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/inc
$(ae4ea10e_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
module_dirs += $(ae4ea10e_prefetcherDno_dirs_0)
module_objs += $(ae4ea10e_prefetcherDno_objs_0)

/Users/DHRUVA/ChampSim/bin/champsim: $(ae4ea10e_prefetcherDno_objs_0)
###
# Build ID: ae4ea10e_prefetcherDno_instr
# Source: /Users/DHRUVA/ChampSim/prefetcher/no_instr
# Destination: /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno_instr
###

ae4ea10e_prefetcherDno_instr_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno_instr
ae4ea10e_prefetcherDno_instr_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/prefetcher/no_instr/%.cc, /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno_instr/%.o, $(wildcard /Users/DHRUVA/ChampSim/prefetcher/no_instr/*.cc))
$(ae4ea10e_prefetcherDno_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/prefetcher/no_instr
$(ae4ea10e_prefetcherDno_instr_objs_0): /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno_instr/%.o: /Users/DHRUVA/ChampSim/prefetcher/no_instr/%.cc | /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno_instr
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/prefetcherDno_instr/*.d)

$(ae4ea10e_prefetcherDno_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
$(ae4ea10e_prefetcherDno_instr_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(ae4ea10e_prefetcherDno_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/inc
$(ae4ea10e_prefetcherDno_instr_objs_0): CPPFLAGS += -include prefetcherDno_instr.inc
module_dirs += $(ae4ea10e_prefetcherDno_instr_dirs_0)
module_objs += $(ae4ea10e_prefetcherDno_instr_objs_0)

/Users/DHRUVA/ChampSim/bin/champsim: $(ae4ea10e_prefetcherDno_instr_objs_0)
###
# Build ID: ae4ea10e_replacementDlru
# Source: /Users/DHRUVA/ChampSim/replacement/lru
# Destination: /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDlru
###

ae4ea10e_replacementDlru_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDlru
ae4ea10e_replacementDlru_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/replacement/lru/%.cc, /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDlru/%.o, $(wildcard /Users/DHRUVA/ChampSim/replacement/lru/*.cc))
$(ae4ea10e_replacementDlru_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/replacement/lru
$(ae4ea10e_replacementDlru_objs_0): /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDlru/%.o: /Users/DHRUVA/ChampSim/replacement/lru/%.cc | /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDlru
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDlru/*.d)

$(ae4ea10e_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
$(ae4ea10e_replacementDlru_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(ae4ea10e_replacementDlru_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/inc
$(ae4ea10e_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
module_dirs += $(ae4ea10e_replacementDlru_dirs_0)
module_objs += $(ae4ea10e_replacementDlru_objs_0)

/Users/DHRUVA/ChampSim/bin/champsim: $(ae4ea10e_replacementDlru_objs_0)
###
# Build ID: ae4ea10e_replacementDship
# Source: /Users/DHRUVA/ChampSim/replacement/ship
# Destination: /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDship
###

ae4ea10e_replacementDship_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDship
ae4ea10e_replacementDship_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/replacement/ship/%.cc, /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDship/%.o, $(wildcard /Users/DHRUVA/ChampSim/replacement/ship/*.cc))
$(ae4ea10e_replacementDship_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/replacement/ship
$(ae4ea10e_replacementDship_objs_0): /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDship/%.o: /Users/DHRUVA/ChampSim/replacement/ship/%.cc | /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDship
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/replacementDship/*.d)

$(ae4ea10e_replacementDship_objs_0): CXXFLAGS += -Wno-unused-parameter
$(ae4ea10e_replacementDship_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(ae4ea10e_replacementDship_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/ae4ea10e/inc
$(ae4ea10e_replacementDship_objs_0): CPPFLAGS += -include replacementDship.inc
module_dirs += $(ae4ea10e_replacementDship_dirs_0)
module_objs += $(ae4ea10e_replacementDship_objs_0)

/Users/DHRUVA/ChampSim/bin/champsim: $(ae4ea10e_replacementDship_objs_0)

######
# Build ID: cb06b815
# Executable: /Users/DHRUVA/ChampSim/test/bin/000-test-main
######

###
# Build ID: cb06b815
# Source: /Users/DHRUVA/ChampSim/test/cpp/src
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj
###

cb06b815_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj
cb06b815_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/test/cpp/src/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj/%.o, $(wildcard /Users/DHRUVA/ChampSim/test/cpp/src/*.cc))
$(cb06b815_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/test/cpp/src
$(cb06b815_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj/%.o: /Users/DHRUVA/ChampSim/test/cpp/src/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj/*.d)

###
# Build ID: cb06b815
# Source: /Users/DHRUVA/ChampSim/src
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj
###

cb06b815_dirs_1 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj
cb06b815_objs_1 = $(patsubst /Users/DHRUVA/ChampSim/src/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj/%.o, $(wildcard /Users/DHRUVA/ChampSim/src/*.cc))
$(cb06b815_objs_1): CPPFLAGS += -I/Users/DHRUVA/ChampSim/src
$(cb06b815_objs_1): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj/%.o: /Users/DHRUVA/ChampSim/src/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/obj/*.d)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_objs_0) $(cb06b815_objs_1) | /Users/DHRUVA/ChampSim/test/bin
$(cb06b815_objs_0) $(cb06b815_objs_1): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
build_dirs += $(cb06b815_dirs_0) $(cb06b815_dirs_1) /Users/DHRUVA/ChampSim/test/bin
build_objs += $(cb06b815_objs_0) $(cb06b815_objs_1)
executable_name += /Users/DHRUVA/ChampSim/test/bin/000-test-main

###
# Build ID: cb06b815_btbDbasic_btb
# Source: /Users/DHRUVA/ChampSim/btb/basic_btb
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/btbDbasic_btb
###

cb06b815_btbDbasic_btb_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/btbDbasic_btb
cb06b815_btbDbasic_btb_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/btb/basic_btb/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/btbDbasic_btb/%.o, $(wildcard /Users/DHRUVA/ChampSim/btb/basic_btb/*.cc))
$(cb06b815_btbDbasic_btb_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/btb/basic_btb
$(cb06b815_btbDbasic_btb_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/btbDbasic_btb/%.o: /Users/DHRUVA/ChampSim/btb/basic_btb/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/btbDbasic_btb
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/btbDbasic_btb/*.d)

$(cb06b815_btbDbasic_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_btbDbasic_btb_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_btbDbasic_btb_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_btbDbasic_btb_objs_0): CPPFLAGS += -include btbDbasic_btb.inc
module_dirs += $(cb06b815_btbDbasic_btb_dirs_0)
module_objs += $(cb06b815_btbDbasic_btb_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_btbDbasic_btb_objs_0)
###
# Build ID: cb06b815_branchDbimodal
# Source: /Users/DHRUVA/ChampSim/branch/bimodal
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDbimodal
###

cb06b815_branchDbimodal_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDbimodal
cb06b815_branchDbimodal_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/branch/bimodal/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDbimodal/%.o, $(wildcard /Users/DHRUVA/ChampSim/branch/bimodal/*.cc))
$(cb06b815_branchDbimodal_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/branch/bimodal
$(cb06b815_branchDbimodal_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDbimodal/%.o: /Users/DHRUVA/ChampSim/branch/bimodal/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDbimodal
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDbimodal/*.d)

$(cb06b815_branchDbimodal_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_branchDbimodal_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_branchDbimodal_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_branchDbimodal_objs_0): CPPFLAGS += -include branchDbimodal.inc
module_dirs += $(cb06b815_branchDbimodal_dirs_0)
module_objs += $(cb06b815_branchDbimodal_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_branchDbimodal_objs_0)
###
# Build ID: cb06b815_branchDgshare
# Source: /Users/DHRUVA/ChampSim/branch/gshare
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDgshare
###

cb06b815_branchDgshare_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDgshare
cb06b815_branchDgshare_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/branch/gshare/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDgshare/%.o, $(wildcard /Users/DHRUVA/ChampSim/branch/gshare/*.cc))
$(cb06b815_branchDgshare_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/branch/gshare
$(cb06b815_branchDgshare_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDgshare/%.o: /Users/DHRUVA/ChampSim/branch/gshare/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDgshare
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDgshare/*.d)

$(cb06b815_branchDgshare_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_branchDgshare_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_branchDgshare_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_branchDgshare_objs_0): CPPFLAGS += -include branchDgshare.inc
module_dirs += $(cb06b815_branchDgshare_dirs_0)
module_objs += $(cb06b815_branchDgshare_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_branchDgshare_objs_0)
###
# Build ID: cb06b815_branchDhashed_perceptron
# Source: /Users/DHRUVA/ChampSim/branch/hashed_perceptron
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDhashed_perceptron
###

cb06b815_branchDhashed_perceptron_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDhashed_perceptron
cb06b815_branchDhashed_perceptron_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/branch/hashed_perceptron/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDhashed_perceptron/%.o, $(wildcard /Users/DHRUVA/ChampSim/branch/hashed_perceptron/*.cc))
$(cb06b815_branchDhashed_perceptron_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/branch/hashed_perceptron
$(cb06b815_branchDhashed_perceptron_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDhashed_perceptron/%.o: /Users/DHRUVA/ChampSim/branch/hashed_perceptron/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDhashed_perceptron
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDhashed_perceptron/*.d)

$(cb06b815_branchDhashed_perceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_branchDhashed_perceptron_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_branchDhashed_perceptron_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_branchDhashed_perceptron_objs_0): CPPFLAGS += -include branchDhashed_perceptron.inc
module_dirs += $(cb06b815_branchDhashed_perceptron_dirs_0)
module_objs += $(cb06b815_branchDhashed_perceptron_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_branchDhashed_perceptron_objs_0)
###
# Build ID: cb06b815_branchDperceptron
# Source: /Users/DHRUVA/ChampSim/branch/perceptron
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDperceptron
###

cb06b815_branchDperceptron_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDperceptron
cb06b815_branchDperceptron_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/branch/perceptron/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDperceptron/%.o, $(wildcard /Users/DHRUVA/ChampSim/branch/perceptron/*.cc))
$(cb06b815_branchDperceptron_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/branch/perceptron
$(cb06b815_branchDperceptron_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDperceptron/%.o: /Users/DHRUVA/ChampSim/branch/perceptron/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDperceptron
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/branchDperceptron/*.d)

$(cb06b815_branchDperceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_branchDperceptron_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_branchDperceptron_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_branchDperceptron_objs_0): CPPFLAGS += -include branchDperceptron.inc
module_dirs += $(cb06b815_branchDperceptron_dirs_0)
module_objs += $(cb06b815_branchDperceptron_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_branchDperceptron_objs_0)
###
# Build ID: cb06b815_prefetcherDip_stride
# Source: /Users/DHRUVA/ChampSim/prefetcher/ip_stride
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDip_stride
###

cb06b815_prefetcherDip_stride_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDip_stride
cb06b815_prefetcherDip_stride_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/prefetcher/ip_stride/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDip_stride/%.o, $(wildcard /Users/DHRUVA/ChampSim/prefetcher/ip_stride/*.cc))
$(cb06b815_prefetcherDip_stride_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/prefetcher/ip_stride
$(cb06b815_prefetcherDip_stride_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDip_stride/%.o: /Users/DHRUVA/ChampSim/prefetcher/ip_stride/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDip_stride
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDip_stride/*.d)

$(cb06b815_prefetcherDip_stride_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_prefetcherDip_stride_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_prefetcherDip_stride_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_prefetcherDip_stride_objs_0): CPPFLAGS += -include prefetcherDip_stride.inc
module_dirs += $(cb06b815_prefetcherDip_stride_dirs_0)
module_objs += $(cb06b815_prefetcherDip_stride_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_prefetcherDip_stride_objs_0)
###
# Build ID: cb06b815_prefetcherDnext_line
# Source: /Users/DHRUVA/ChampSim/prefetcher/next_line
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line
###

cb06b815_prefetcherDnext_line_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line
cb06b815_prefetcherDnext_line_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/prefetcher/next_line/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line/%.o, $(wildcard /Users/DHRUVA/ChampSim/prefetcher/next_line/*.cc))
$(cb06b815_prefetcherDnext_line_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/prefetcher/next_line
$(cb06b815_prefetcherDnext_line_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line/%.o: /Users/DHRUVA/ChampSim/prefetcher/next_line/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line/*.d)

$(cb06b815_prefetcherDnext_line_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_prefetcherDnext_line_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_prefetcherDnext_line_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_prefetcherDnext_line_objs_0): CPPFLAGS += -include prefetcherDnext_line.inc
module_dirs += $(cb06b815_prefetcherDnext_line_dirs_0)
module_objs += $(cb06b815_prefetcherDnext_line_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_prefetcherDnext_line_objs_0)
###
# Build ID: cb06b815_prefetcherDnext_line_instr
# Source: /Users/DHRUVA/ChampSim/prefetcher/next_line_instr
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line_instr
###

cb06b815_prefetcherDnext_line_instr_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line_instr
cb06b815_prefetcherDnext_line_instr_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/prefetcher/next_line_instr/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line_instr/%.o, $(wildcard /Users/DHRUVA/ChampSim/prefetcher/next_line_instr/*.cc))
$(cb06b815_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/prefetcher/next_line_instr
$(cb06b815_prefetcherDnext_line_instr_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line_instr/%.o: /Users/DHRUVA/ChampSim/prefetcher/next_line_instr/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line_instr
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDnext_line_instr/*.d)

$(cb06b815_prefetcherDnext_line_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -include prefetcherDnext_line_instr.inc
module_dirs += $(cb06b815_prefetcherDnext_line_instr_dirs_0)
module_objs += $(cb06b815_prefetcherDnext_line_instr_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_prefetcherDnext_line_instr_objs_0)
###
# Build ID: cb06b815_prefetcherDno
# Source: /Users/DHRUVA/ChampSim/prefetcher/no
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno
###

cb06b815_prefetcherDno_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno
cb06b815_prefetcherDno_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/prefetcher/no/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno/%.o, $(wildcard /Users/DHRUVA/ChampSim/prefetcher/no/*.cc))
$(cb06b815_prefetcherDno_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/prefetcher/no
$(cb06b815_prefetcherDno_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno/%.o: /Users/DHRUVA/ChampSim/prefetcher/no/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno/*.d)

$(cb06b815_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_prefetcherDno_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_prefetcherDno_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
module_dirs += $(cb06b815_prefetcherDno_dirs_0)
module_objs += $(cb06b815_prefetcherDno_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_prefetcherDno_objs_0)
###
# Build ID: cb06b815_prefetcherDno_instr
# Source: /Users/DHRUVA/ChampSim/prefetcher/no_instr
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno_instr
###

cb06b815_prefetcherDno_instr_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno_instr
cb06b815_prefetcherDno_instr_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/prefetcher/no_instr/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno_instr/%.o, $(wildcard /Users/DHRUVA/ChampSim/prefetcher/no_instr/*.cc))
$(cb06b815_prefetcherDno_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/prefetcher/no_instr
$(cb06b815_prefetcherDno_instr_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno_instr/%.o: /Users/DHRUVA/ChampSim/prefetcher/no_instr/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno_instr
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDno_instr/*.d)

$(cb06b815_prefetcherDno_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_prefetcherDno_instr_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_prefetcherDno_instr_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_prefetcherDno_instr_objs_0): CPPFLAGS += -include prefetcherDno_instr.inc
module_dirs += $(cb06b815_prefetcherDno_instr_dirs_0)
module_objs += $(cb06b815_prefetcherDno_instr_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_prefetcherDno_instr_objs_0)
###
# Build ID: cb06b815_prefetcherDspp_dev
# Source: /Users/DHRUVA/ChampSim/prefetcher/spp_dev
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDspp_dev
###

cb06b815_prefetcherDspp_dev_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDspp_dev
cb06b815_prefetcherDspp_dev_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/prefetcher/spp_dev/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDspp_dev/%.o, $(wildcard /Users/DHRUVA/ChampSim/prefetcher/spp_dev/*.cc))
$(cb06b815_prefetcherDspp_dev_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/prefetcher/spp_dev
$(cb06b815_prefetcherDspp_dev_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDspp_dev/%.o: /Users/DHRUVA/ChampSim/prefetcher/spp_dev/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDspp_dev
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDspp_dev/*.d)

$(cb06b815_prefetcherDspp_dev_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_prefetcherDspp_dev_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_prefetcherDspp_dev_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_prefetcherDspp_dev_objs_0): CPPFLAGS += -include prefetcherDspp_dev.inc
module_dirs += $(cb06b815_prefetcherDspp_dev_dirs_0)
module_objs += $(cb06b815_prefetcherDspp_dev_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_prefetcherDspp_dev_objs_0)
###
# Build ID: cb06b815_prefetcherDva_ampm_lite
# Source: /Users/DHRUVA/ChampSim/prefetcher/va_ampm_lite
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDva_ampm_lite
###

cb06b815_prefetcherDva_ampm_lite_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDva_ampm_lite
cb06b815_prefetcherDva_ampm_lite_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/prefetcher/va_ampm_lite/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDva_ampm_lite/%.o, $(wildcard /Users/DHRUVA/ChampSim/prefetcher/va_ampm_lite/*.cc))
$(cb06b815_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/prefetcher/va_ampm_lite
$(cb06b815_prefetcherDva_ampm_lite_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDva_ampm_lite/%.o: /Users/DHRUVA/ChampSim/prefetcher/va_ampm_lite/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDva_ampm_lite
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/prefetcherDva_ampm_lite/*.d)

$(cb06b815_prefetcherDva_ampm_lite_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -include prefetcherDva_ampm_lite.inc
module_dirs += $(cb06b815_prefetcherDva_ampm_lite_dirs_0)
module_objs += $(cb06b815_prefetcherDva_ampm_lite_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_prefetcherDva_ampm_lite_objs_0)
###
# Build ID: cb06b815_testDcppDmodulesDprefetcherDaddress_collector
# Source: /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/address_collector
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDaddress_collector
###

cb06b815_testDcppDmodulesDprefetcherDaddress_collector_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDaddress_collector
cb06b815_testDcppDmodulesDprefetcherDaddress_collector_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/address_collector/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDaddress_collector/%.o, $(wildcard /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/address_collector/*.cc))
$(cb06b815_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/address_collector
$(cb06b815_testDcppDmodulesDprefetcherDaddress_collector_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDaddress_collector/%.o: /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/address_collector/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDaddress_collector
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDaddress_collector/*.d)

$(cb06b815_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDaddress_collector.inc
module_dirs += $(cb06b815_testDcppDmodulesDprefetcherDaddress_collector_dirs_0)
module_objs += $(cb06b815_testDcppDmodulesDprefetcherDaddress_collector_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_testDcppDmodulesDprefetcherDaddress_collector_objs_0)
###
# Build ID: cb06b815_testDcppDmodulesDprefetcherDmetadata_collector
# Source: /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/metadata_collector
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_collector
###

cb06b815_testDcppDmodulesDprefetcherDmetadata_collector_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_collector
cb06b815_testDcppDmodulesDprefetcherDmetadata_collector_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/metadata_collector/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_collector/%.o, $(wildcard /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/metadata_collector/*.cc))
$(cb06b815_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/metadata_collector
$(cb06b815_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_collector/%.o: /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/metadata_collector/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_collector
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_collector/*.d)

$(cb06b815_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDmetadata_collector.inc
module_dirs += $(cb06b815_testDcppDmodulesDprefetcherDmetadata_collector_dirs_0)
module_objs += $(cb06b815_testDcppDmodulesDprefetcherDmetadata_collector_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_testDcppDmodulesDprefetcherDmetadata_collector_objs_0)
###
# Build ID: cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter
# Source: /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/metadata_emitter
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_emitter
###

cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_emitter
cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/metadata_emitter/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_emitter/%.o, $(wildcard /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/metadata_emitter/*.cc))
$(cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/metadata_emitter
$(cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_emitter/%.o: /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/metadata_emitter/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_emitter
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDmetadata_emitter/*.d)

$(cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDmetadata_emitter.inc
module_dirs += $(cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter_dirs_0)
module_objs += $(cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0)
###
# Build ID: cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector
# Source: /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDprefetch_hit_collector
###

cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDprefetch_hit_collector
cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDprefetch_hit_collector/%.o, $(wildcard /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector/*.cc))
$(cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector
$(cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDprefetch_hit_collector/%.o: /Users/DHRUVA/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDprefetch_hit_collector
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDprefetcherDprefetch_hit_collector/*.d)

$(cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDprefetch_hit_collector.inc
module_dirs += $(cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector_dirs_0)
module_objs += $(cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0)
###
# Build ID: cb06b815_replacementDdrrip
# Source: /Users/DHRUVA/ChampSim/replacement/drrip
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDdrrip
###

cb06b815_replacementDdrrip_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDdrrip
cb06b815_replacementDdrrip_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/replacement/drrip/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDdrrip/%.o, $(wildcard /Users/DHRUVA/ChampSim/replacement/drrip/*.cc))
$(cb06b815_replacementDdrrip_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/replacement/drrip
$(cb06b815_replacementDdrrip_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDdrrip/%.o: /Users/DHRUVA/ChampSim/replacement/drrip/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDdrrip
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDdrrip/*.d)

$(cb06b815_replacementDdrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_replacementDdrrip_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_replacementDdrrip_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_replacementDdrrip_objs_0): CPPFLAGS += -include replacementDdrrip.inc
module_dirs += $(cb06b815_replacementDdrrip_dirs_0)
module_objs += $(cb06b815_replacementDdrrip_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_replacementDdrrip_objs_0)
###
# Build ID: cb06b815_replacementDlru
# Source: /Users/DHRUVA/ChampSim/replacement/lru
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDlru
###

cb06b815_replacementDlru_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDlru
cb06b815_replacementDlru_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/replacement/lru/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDlru/%.o, $(wildcard /Users/DHRUVA/ChampSim/replacement/lru/*.cc))
$(cb06b815_replacementDlru_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/replacement/lru
$(cb06b815_replacementDlru_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDlru/%.o: /Users/DHRUVA/ChampSim/replacement/lru/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDlru
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDlru/*.d)

$(cb06b815_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_replacementDlru_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_replacementDlru_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
module_dirs += $(cb06b815_replacementDlru_dirs_0)
module_objs += $(cb06b815_replacementDlru_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_replacementDlru_objs_0)
###
# Build ID: cb06b815_replacementDship
# Source: /Users/DHRUVA/ChampSim/replacement/ship
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDship
###

cb06b815_replacementDship_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDship
cb06b815_replacementDship_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/replacement/ship/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDship/%.o, $(wildcard /Users/DHRUVA/ChampSim/replacement/ship/*.cc))
$(cb06b815_replacementDship_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/replacement/ship
$(cb06b815_replacementDship_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDship/%.o: /Users/DHRUVA/ChampSim/replacement/ship/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDship
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDship/*.d)

$(cb06b815_replacementDship_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_replacementDship_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_replacementDship_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_replacementDship_objs_0): CPPFLAGS += -include replacementDship.inc
module_dirs += $(cb06b815_replacementDship_dirs_0)
module_objs += $(cb06b815_replacementDship_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_replacementDship_objs_0)
###
# Build ID: cb06b815_replacementDsrrip
# Source: /Users/DHRUVA/ChampSim/replacement/srrip
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDsrrip
###

cb06b815_replacementDsrrip_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDsrrip
cb06b815_replacementDsrrip_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/replacement/srrip/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDsrrip/%.o, $(wildcard /Users/DHRUVA/ChampSim/replacement/srrip/*.cc))
$(cb06b815_replacementDsrrip_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/replacement/srrip
$(cb06b815_replacementDsrrip_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDsrrip/%.o: /Users/DHRUVA/ChampSim/replacement/srrip/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDsrrip
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/replacementDsrrip/*.d)

$(cb06b815_replacementDsrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_replacementDsrrip_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_replacementDsrrip_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_replacementDsrrip_objs_0): CPPFLAGS += -include replacementDsrrip.inc
module_dirs += $(cb06b815_replacementDsrrip_dirs_0)
module_objs += $(cb06b815_replacementDsrrip_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_replacementDsrrip_objs_0)
###
# Build ID: cb06b815_testDcppDmodulesDreplacementDlru_collect
# Source: /Users/DHRUVA/ChampSim/test/cpp/modules/replacement/lru_collect
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDlru_collect
###

cb06b815_testDcppDmodulesDreplacementDlru_collect_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDlru_collect
cb06b815_testDcppDmodulesDreplacementDlru_collect_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/test/cpp/modules/replacement/lru_collect/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDlru_collect/%.o, $(wildcard /Users/DHRUVA/ChampSim/test/cpp/modules/replacement/lru_collect/*.cc))
$(cb06b815_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/test/cpp/modules/replacement/lru_collect
$(cb06b815_testDcppDmodulesDreplacementDlru_collect_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDlru_collect/%.o: /Users/DHRUVA/ChampSim/test/cpp/modules/replacement/lru_collect/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDlru_collect
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDlru_collect/*.d)

$(cb06b815_testDcppDmodulesDreplacementDlru_collect_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -include testDcppDmodulesDreplacementDlru_collect.inc
module_dirs += $(cb06b815_testDcppDmodulesDreplacementDlru_collect_dirs_0)
module_objs += $(cb06b815_testDcppDmodulesDreplacementDlru_collect_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_testDcppDmodulesDreplacementDlru_collect_objs_0)
###
# Build ID: cb06b815_testDcppDmodulesDreplacementDmock_replacement
# Source: /Users/DHRUVA/ChampSim/test/cpp/modules/replacement/mock_replacement
# Destination: /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDmock_replacement
###

cb06b815_testDcppDmodulesDreplacementDmock_replacement_dirs_0 = /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDmock_replacement
cb06b815_testDcppDmodulesDreplacementDmock_replacement_objs_0 = $(patsubst /Users/DHRUVA/ChampSim/test/cpp/modules/replacement/mock_replacement/%.cc, /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDmock_replacement/%.o, $(wildcard /Users/DHRUVA/ChampSim/test/cpp/modules/replacement/mock_replacement/*.cc))
$(cb06b815_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/test/cpp/modules/replacement/mock_replacement
$(cb06b815_testDcppDmodulesDreplacementDmock_replacement_objs_0): /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDmock_replacement/%.o: /Users/DHRUVA/ChampSim/test/cpp/modules/replacement/mock_replacement/%.cc | /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDmock_replacement
-include $(wildcard /Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/testDcppDmodulesDreplacementDmock_replacement/*.d)

$(cb06b815_testDcppDmodulesDreplacementDmock_replacement_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cb06b815_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cb06b815_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -I/Users/DHRUVA/ChampSim/.csconfig/test/cb06b815/inc
$(cb06b815_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -include testDcppDmodulesDreplacementDmock_replacement.inc
module_dirs += $(cb06b815_testDcppDmodulesDreplacementDmock_replacement_dirs_0)
module_objs += $(cb06b815_testDcppDmodulesDreplacementDmock_replacement_objs_0)

/Users/DHRUVA/ChampSim/test/bin/000-test-main: $(cb06b815_testDcppDmodulesDreplacementDmock_replacement_objs_0)
